### ISSUE TITLE
Admin: Test Checkboxes

### ISSUE THREAD

**Issue by u20431644** [JCP-Team/GDRT2022#3]
Please tick the box with your name next to it:
- [x] Zander @GitM3 
- [x] Matthew @MJ-stack 
- [x] Doné @d-joubert 
- [ ] Tebogo
- [ ] Sam

**Comment by d-joubert** [comment]
I am still having trouble accessing the checkboxes; they are all greyed out on my side.

**Comment by u20431644** [comment]
> I am still having trouble accessing the checkboxes; they are all greyed out on my side.

Hi Doné, Zander @GitM3 and I are going to sit down and fix this soon.
Regards
